### ISSUE TITLE
Implement new Experiment Room

### ISSUE THREAD

**Issue by michaelholly** [GamesResearchTUG/Maroon#124]

**Comment by codecreativity** [comment]
The new look is good, the interaction feels much better if you can walk through the visualization and see everything from all sides.

Possible problems:
- The light is very bright, if you are in the room for a longer time it starts to strain the eyes and distracts from the actual experiment
- The console is too far away from the intractable experiment. Ideally you should be able to refine the parameters and interact with the magnet without teleporting in between

**Comment by codecreativity** [comment]
I merged #122 now, but I'll leave this issue open in order to keep these issues in mind

**Comment by codecreativity** [comment]
See #167 for current progress on this matter
