### ISSUE TITLE
Clock is not synchronized

### ISSUE THREAD

**Issue by JMetalian** [GamesResearchTUG/Maroon#386]
**Describe the defect**
The clock in the lab is not synchronized with the system. Behaves randomly, meaning that, sometimes it shows the correct time and sometimes not.

**To Reproduce**
1. Go to clock on the wall
4. See the error when you compare with system clock.

**Expected behavior**
The correct time should be visible.

**Found in version**
The version where the defect was detected v4.2 -> build: 20211213

**Screenshots**
![image](https://user-images.githubusercontent.com/43638551/149505836-7ed54c6e-2e2b-4333-a6a3-382d2889f825.png)

**WebGL:**
OS: Windows 10, 21H2 Build: 19044.1415
Browser: Chrome
Version 97.0.4692.71

**Comment by FlorianGlawogger** [comment]
For me the time initially was always correct, however, if you pause Maroon, then return, the time will not jump to the new real-life time, but instead continue when you paused
