### ISSUE TITLE
Bump version of unity-builder 

### ISSUE THREAD

**Issue by mfbrantner** [GamesResearchTUG/Maroon#452]
The action [unity-builder](https://github.com/game-ci/unity-builder) currently uses version 2. It can now be bumped to version 3.

Upgrading unity-builder requires a slight change to the build script, since it searches for a [certain string](https://github.com/game-ci/unity-builder/issues/564) in the log.

Note: Version 3 of [unity-test-runner](https://github.com/game-ci/unity-test-runner) is also available, but there appears to be an issue with the edit-mode tests running indefinitely, so it should stay on v2 for the time being.

**Comment by FlorianGlawogger** [comment]
Since the last builds with the v3 version did not work correctly, the PR #453 got reverted again via #458.

**Comment by FlorianGlawogger** [comment]
According to https://github.com/game-ci/unity-builder/pull/596 v4 of the UnityBuilder should handle the errors the same way as v2 did, maybe we can skip v3 and immediately go to v4?

**Comment by FlorianGlawogger** [comment]
unity-builder v4 has been merged into develop with #457
