### ISSUE TITLE
Network Simulator V2

### ISSUE THREAD

**Issue by jousefvanm** [GamesResearchTUG/Maroon#456]
We want to have a better version of a network simulator. This should initially only work for PC - VR should not be completely ignored regarding design decisions, we most likely will extend this experiment to support VR later.

The primary goal of the experiment is to illustrate the functions performed by different network devices within a typical home network. To do this, the user can become a network device in this simulated network and perform the tasks by himself. The network layout is static, it can't be manipulated by the user. 

**Supported devices**
- Hub
- Switch (Shown as an extension of a hub)
- End device
- Router

We limit the functionality of all devices to support operations inside the LAN apart from the general packet forwarding to the default gateway. We treat the connection to the outer world like an ISP connection in a typical home network - A kind of black box that delivers and accepts packets.

**Learning goals**
- MAC, IPv4, Subnet-Mask, Network-Address
- SAT, ARP, DHCP, DNS
- Routes of packet inside LAN with external or internal destination IPs

The layers of a packet follow the TCP/IP model, not the OSI model. This means that the packet representation is defined as letters in envelopes. Each envelope that is recursively applied to the letter applies to one of the 4 layers. This means that the header data of the layer (e.g. destination IP in the Internet layer) can be read and written on the envelope itself.

**Comment by FlorianGlawogger** [comment]
Closed, as no longer pursued
