### ISSUE TITLE
Coulomb's Law

### ISSUE THREAD

**Issue by sandra1001** [GamesResearchTUG/Maroon#46]
**2d Mode**
- [x] Whiteboard
- [x] Create charges with different charge levels (-5 - 5) and fixed position
- [x] Vector Field Arrow Visualization
- [x] Shader included
- [ ] Field Lines
- [x] potential differences (between two points) with voltometre

**3d Mode**
- [x] 3d moving cube (incl. shader) and shortcut movement
- [x] Create charges with different charge levels (-5 - 5) and fixed position
- [ ] Field Lines
- [x] Moveable shader plates for iron field, voltage etc. visualization
- [x] Vector Field Arrow Visualization
- [x] Shader included
- [x] potential differences (between two points) with voltometre
- [x] camera zoom with mousewheel and +/- buttons

**VR:**

**Shader:**
- [x] Iron Field Visualization
- [x] Voltage Visualization
- [x] Equipotential Line Visualization

**General** 
- [x] Coulomb Logic Movement
- [x] Double click on the charge in the UI positions it in the middle
- [x] Count that max. 20 charges can be used
- [x] normal reset resets positions, whole reset deletes all charges
- [x] Switch between 2d and 3d
- [x] arrow movement for charges
- [x] evtl. particle name change to charge
- [x] UI: when click on Iron Field Visualization and the visualization is turned on -> turn it off
- [ ] Shortcuts should be explained by help character
- [x] statt BField EField verwenden, BFieldDyn löschen und stattdessen BField bzw. EField updaten mit bool isDynamic

**Comment by michaelholly** [comment]
Can we close this issue, as we have completed the pull request?
For the open points, I would suggest creating new issues.
