### ISSUE TITLE
Cathode Ray Tube experiment information text size changes

### ISSUE THREAD

**Issue by FlorianGlawogger** [GamesResearchTUG/Maroon#484]
**Describe the defect**
When clicking on show formulas and then back on show information, the text size of that information changes.

**To Reproduce**
1. Go to Cathode Ray Tube experiment
2. Click on show formulas
3. click on Show information
4. The text size of the text fields below the Fx/fy/fz has changed a lot

**Expected behavior**
I expect the text size to be the same.

**Found in version**
build 2024-05-22

**Screenshots**
At the start:
![grafik](https://github.com/GameLabGraz/Maroon/assets/73254596/89fa2c91-196f-44f2-aa29-cb889fab4280)
After showing formulas and going then back to showing information:
![grafik](https://github.com/GameLabGraz/Maroon/assets/73254596/678d3889-6750-49e7-b191-74f35e3665cf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by flowmdev** [comment]
Tested it on Windows 11, with different screen resolutions. Started the experiment directly from its origin scene and also from the main menu. Could not reproduce the issue. For me, the text size is always set to the size of the second image. It never becomes as small as depicted in image 1. Maybe, this issue got fixed already, @FlorianGlawogger?

**Comment by FlorianGlawogger** [comment]
Hmm, on https://maroon.tugraz.at/build/web/ it's still happening for me, but on the current development branch it seems like the issue is fixed for me as well; closing the issue 👍
