### ISSUE TITLE
3D Motion Simulation experiment always has a "Description" text

### ISSUE THREAD

**Issue by FlorianGlawogger** [GamesResearchTUG/Maroon#485]
**Describe the defect**
In the 3D Motion simulation experiment, in the top left corner there is always a "Description, Description here" text. Seems a bit unnecessary. One could show the title of the preset there, or just remove it altogether if it's not used.

**Found in version**
2024-05-22

**Screenshots**
![grafik](https://github.com/GameLabGraz/Maroon/assets/73254596/85f09510-98f2-41d6-a5ed-a9fb6115f676)
![grafik](https://github.com/GameLabGraz/Maroon/assets/73254596/88af731c-bc50-4538-a37b-90f99d9a2d63)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by flowmdev** [comment]
Closed by #465
