### ISSUE TITLE
CI/CD Unity license expired 

### ISSUE THREAD

**Issue by mfbrantner** [GamesResearchTUG/Maroon#510]
Workflow runs are currently failing because the serial number used for CI is expired.

`[Licensing::Client] Error: Code 20113 while processing request (status: serial expired on Sat Aug 24 12:36:42 GMT 2024)`

To fix this, I assume that someone with necessary permissions must update the `UNITY_SERIAL` secret located at Settings -> Secrets and variables -> Actions.

I've manually disabled the workflow until this is resolved.

**Comment by FlorianGlawogger** [comment]
FYI: @michaelholly just updated the serial secret 👍

**Comment by mfbrantner** [comment]
Thank you! I'll mark this as completed :slightly_smiling_face:
