### ISSUE TITLE
[VR] Welcome Room

### ISSUE THREAD

**Issue by michaelholly** [GamesResearchTUG/Maroon#85]
A "Welcome" room is needed where the users can learn how to work with Maroon VR and other VR applications. It should be a starting point of all our future VR applications which showcases how to work with VR (interactions with the controller etc).

Brainstorming session:
https://1drv.ms/o/s!BBK2MkMZnFsAkxQiMW5QsdLLmXa_?e=qjsTfCNS6Eqg8SNQ_5jJTw&at=9

**Comment by codecreativity** [comment]
Welcome room got moved to a separate project. Follow issues there.
